apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket
  template:
    metadata:
      labels:
        app: websocket
    spec:
      containers:
        - name: websocket
          image: mirzaahmed03/chat-app-websocket:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
